#!/bin/bash
echo "+-------------------------------+"
echo "| Backup to portable USB drive  |"
echo "+-------------------------------+"
echo
printf \
"+-------------------------------+
| what the hell                 |
+-------------------------------+\n"
     
